print('***** DESAFIO 01 *****')
nome = input('Qual o seu nome? ')
print('Olá', nome,', prazer em te conhecer.\n')
dia = input('Qual o dia do seu nascimento? ')
mes = input('Qual o mês do seu nascimento? ')
ano = input('Qual o ano do seu nascimento? ')
print(nome, 'você nasceu no dia',dia,'de', mes, 'de', ano,'correto?')
